/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RgsXPxH8t3P
 */
import { Button } from '@nextui-org/react';
import { Input } from '@nextui-org/react';
import Link from 'next/link';
import Image from 'next/image';

function Home() {
	return (
		<>
			<div className="bg-gray-50 py-6 lg:py-12">
				<div className="container px-4 grid items-center gap-4 text-center md:px-6">
					<div className="space-y-3">
						<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
							Explore the Best Dishes
						</h2>
						<p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
							Discover the most delicious dishes in your area. From appetizers
							to desserts, we&apos;ve got you covered.
						</p>
					</div>
					<div className="mx-auto grid max-w-sm gap-2 items-center justify-center sm:max-w-none sm:grid-cols-4 lg:gap-4">
						<div className="relative w-full group">
							<Image
								alt="Food"
								className="rounded-lg object-cover"
								height="200"
								src="./200.svg"
								style={{
									aspectRatio: '200/200',
									objectFit: 'cover',
								}}
								width="200"
							/>
							<div className="absolute inset-0 flex flex-col items-center justify-center gap-1 transform translate-y-full opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100">
								<Button size="sm" variant="outline">
									View
								</Button>
							</div>
						</div>
						<div className="relative w-full group">
							<Image
								alt="Food"
								className="rounded-lg object-cover"
								height="200"
								src="./200.svg"
								style={{
									aspectRatio: '200/200',
									objectFit: 'cover',
								}}
								width="200"
							/>
							<div className="absolute inset-0 flex flex-col items-center justify-center gap-1 transform translate-y-full opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100">
								<Button size="sm" variant="outline">
									View
								</Button>
							</div>
						</div>
						<div className="relative w-full group">
							<Image
								alt="Food"
								className="rounded-lg object-cover"
								height="200"
								src="./200.svg"
								style={{
									aspectRatio: '200/200',
									objectFit: 'cover',
								}}
								width="200"
							/>
							<div className="absolute inset-0 flex flex-col items-center justify-center gap-1 transform translate-y-full opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100">
								<Button size="sm" variant="outline">
									View
								</Button>
							</div>
						</div>
						<div className="relative w-full group">
							<Image
								alt="Food"
								className="rounded-lg object-cover"
								height="200"
								src="./200.svg"
								style={{
									aspectRatio: '200/200',
									objectFit: 'cover',
								}}
								width="200"
							/>
							<div className="absolute inset-0 flex flex-col items-center justify-center gap-1 transform translate-y-full opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100">
								<Button size="sm" variant="outline">
									View
								</Button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className="py-12 md:py-24 lg:py-32">
				<div className="container px-4 grid items-center gap-4 md:px-6">
					<div className="space-y-3">
						<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
							Top-Rated Restaurants
						</h2>
						<p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
							Explore the best restaurants for every cuisine type. Click on a
							tab to see the top-rated restaurants for that cuisine.
						</p>
					</div>
					<div className="mx-auto max-w-2xl border-b border-gray-200 dark:border-gray-800">
						<nav className="flex items-stretch rounded-lg border border-gray-200 divide-x dark:border-gray-800">
							<Link
								className="flex-1 inline-flex items-center justify-center -mb-1 px-4 text-sm font-semibold"
								href="#"
							>
								All
							</Link>
							<Link
								className="flex-1 inline-flex items-center justify-center -mb-1 px-4 text-sm font-semibold text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
								href="#"
							>
								American
							</Link>
							<Link
								className="flex-1 inline-flex items-center justify-center -mb-1 px-4 text-sm font-semibold text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
								href="#"
							>
								Italian
							</Link>
							<Link
								className="flex-1 inline-flex items-center justify-center -mb-1 px-4 text-sm font-semibold text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
								href="#"
							>
								Mexican
							</Link>
							<Link
								className="flex-1 inline-flex items-center justify-center -mb-1 px-4 text-sm font-semibold text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
								href="#"
							>
								Chinese
							</Link>
						</nav>
					</div>
					<div className="mx-auto grid max-w-sm gap-6 sm:max-w-4xl sm:grid-cols-2 lg:max-w-5xl lg:grid-cols-3">
						<div className="flex flex-col gap-1">
							<Image
								alt="Restaurant"
								className="rounded-lg object-cover aspect-[16/9]"
								height="250"
								src="./250x400.svg"
								width="400"
							/>
							<div className="flex-1 flex flex-col gap-1">
								<h3 className="font-semibold">Mama&apos;s Kitchen</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Italian
								</p>
								<div className="flex items-center gap-1">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<span className="text-xs ml-auto">4.0</span>
								</div>
							</div>
						</div>
						<div className="flex flex-col gap-1">
							<Image
								alt="Restaurant"
								className="rounded-lg object-cover aspect-[16/9]"
								height="250"
								src="./250x400.svg"
								width="400"
							/>
							<div className="flex-1 flex flex-col gap-1">
								<h3 className="font-semibold">Mama&apos;s Kitchen</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Italian
								</p>
								<div className="flex items-center gap-1">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<span className="text-xs ml-auto">4.0</span>
								</div>
							</div>
						</div>
						<div className="flex flex-col gap-1">
							<Image
								alt="Restaurant"
								className="rounded-lg object-cover aspect-[16/9]"
								height="250"
								src="./250x400.svg"
								width="400"
							/>
							<div className="flex-1 flex flex-col gap-1">
								<h3 className="font-semibold">Mama&apos;s Kitchen</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Italian
								</p>
								<div className="flex items-center gap-1">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<span className="text-xs ml-auto">4.0</span>
								</div>
							</div>
						</div>
						<div className="flex flex-col gap-1">
							<Image
								alt="Restaurant"
								className="rounded-lg object-cover aspect-[16/9]"
								height="250"
								src="./250x400.svg"
								width="400"
							/>
							<div className="flex-1 flex flex-col gap-1">
								<h3 className="font-semibold">Mama&apos;s Kitchen</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Italian
								</p>
								<div className="flex items-center gap-1">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<span className="text-xs ml-auto">4.0</span>
								</div>
							</div>
						</div>
						<div className="flex flex-col gap-1">
							<Image
								alt="Restaurant"
								className="rounded-lg object-cover aspect-[16/9]"
								height="250"
								src="./250x400.svg"
								width="400"
							/>
							<div className="flex-1 flex flex-col gap-1">
								<h3 className="font-semibold">Mama&apos;s Kitchen</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Italian
								</p>
								<div className="flex items-center gap-1">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<span className="text-xs ml-auto">4.0</span>
								</div>
							</div>
						</div>
						<div className="flex flex-col gap-1">
							<Image
								alt="Restaurant"
								className="rounded-lg object-cover aspect-[16/9]"
								height="250"
								src="./250x400.svg"
								width="400"
							/>
							<div className="flex-1 flex flex-col gap-1">
								<h3 className="font-semibold">Mama&apos;s Kitchen</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Italian
								</p>
								<div className="flex items-center gap-1">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<span className="text-xs ml-auto">4.0</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className="border-t border-gray-200 dark:border-gray-800">
				<div className="container py-12 md:py-24 lg:py-32 grid gap-4 px-4 text-center md:gap-10 md:px-6">
					<div className="space-y-3">
						<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
							Latest Reviews
						</h2>
						<p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
							Check out the most recent reviews from our community. Find out
							what others are saying about the best dishes and restaurants.
						</p>
					</div>
					<div className="mx-auto max-w-2xl space-y-4 md:max-w-4xl lg:max-w-5xl">
						<div className="grid grid-cols-12 items-start gap-4">
							<div className="col-span-2">
								<Image
									alt="User"
									className="rounded-full object-cover aspect-square"
									height="100"
									src="./100.svg"
									width="100"
								/>
							</div>
							<div className="col-span-10 space-y-2">
								<div className="flex items-center gap-2">
									<h3 className="font-semibold">Alice Johnson</h3>
									<span className="text-xs text-gray-500 dark:text-gray-400">
										2 hours ago
									</span>
								</div>
								<div className="flex items-center gap-2">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
								</div>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									The pasta was delicious, but the service was a bit slow.
									Overall, it&apos;s a nice place for a cozy dinner.
								</p>
							</div>
						</div>
						<div className="grid grid-cols-12 items-start gap-4">
							<div className="col-span-2">
								<Image
									alt="User"
									className="rounded-full object-cover aspect-square"
									height="100"
									src="./100.svg"
									width="100"
								/>
							</div>
							<div className="col-span-10 space-y-2">
								<div className="flex items-center gap-2">
									<h3 className="font-semibold">Bob Smith</h3>
									<span className="text-xs text-gray-500 dark:text-gray-400">
										1 day ago
									</span>
								</div>
								<div className="flex items-center gap-2">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
								</div>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									The tacos here are amazing! I highly recommend the carne asada
									tacos. They are packed with flavor and the meat is so tender.
									This place is a gem.
								</p>
							</div>
						</div>
						<div className="grid grid-cols-12 items-start gap-4">
							<div className="col-span-2">
								<Image
									alt="User"
									className="rounded-full object-cover aspect-square"
									height="100"
									src="./100.svg"
									width="100"
								/>
							</div>
							<div className="col-span-10 space-y-2">
								<div className="flex items-center gap-2">
									<h3 className="font-semibold">Emily Davis</h3>
									<span className="text-xs text-gray-500 dark:text-gray-400">
										3 days ago
									</span>
								</div>
								<div className="flex items-center gap-2">
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
									<StarIcon className="w-4 h-4 fill-gray-100 dark:fill-gray-800" />
								</div>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									The pizza was okay, but I&apos;ve had better. The crust was a
									bit too doughy for my taste. The service was good, though. I
									might give this place another try and order a different dish
									next time.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className="bg-gray-900 py-12 md:py-24 lg:py-32">
				<div className="container grid gap-4 px-4 text-center md:gap-10 md:px-6">
					<div className="space-y-3">
						<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
							Ready to Explore?
						</h2>
						<p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
							Join our community and start sharing your reviews. Discover new
							favorites and let others know about your culinary adventures.
						</p>
					</div>
					<form className="mx-auto max-w-sm space-y-4">
						<div className="flex rounded-lg border">
							<Input
								className="rounded-l-lg"
								placeholder="Enter your email"
								type="email"
							/>
							<Button className="rounded-r-lg" type="submit">
								Sign Up
							</Button>
						</div>
						<p className="text-xs text-gray-500 dark:text-gray-400" />
					</form>
				</div>
			</div>
		</>
	);
}

function StarIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
		</svg>
	);
}

export default Home;
